config/routes.rb
Rails.application.routes.draw do
  resource :language, only: [:update]

  scope "(:locale)", locale: /da/, defaults: {locale: 'en'} do
    namespace :saasy do
      resources :callbacks, only: [:create]
      resources :subscriptions, only: [:show]
    end

    as :user do
      patch 'confirmation' => 'confirmations#update', as: :update_user_confirmation, controller: 'confirmations'
    end

    devise_for :users, {
      path: '',
      path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        sign_out_via: [:delete]
      },
      controllers: {
        confirmations: 'confirmations',
        sessions: 'sessions'
      }
    }

    ActiveAdmin.routes(self)

    root 'home#show'

    resources :wizards, only: [:new, :create]

    get 'autologin/:id' => 'autologins#login', as: :autologin

    namespace :manager do
      root 'profiles#edit'
      resource :profile, only: [:edit, :update]
      resources :product_groups, only: [:index, :show, :create, :edit, :update, :destroy] do
        post :sort, on: :member
      end
      resources :arguments, only: [:destroy]
      resources :users, only: [:index, :create, :edit, :update, :destroy]
      namespace :reports do
        root 'dashboard#show'
        resource :user_activity, only: [:show]
        resource :argument_ranking, only: [:show]
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :auth, only: [:create]
      match 'resources', to: 'resources#index', via: [:get, :post]
      resource :passwords, only: [:create, :update]
      resource :profile, only: [:show] do
        resource :avatar, only: [:update]
      end
      resources :arguments, only: [:create, :update] do
        resource :ratings, only: [:create]
      end
    end
  end

  comfy_route :cms_admin, path: '/admin/cms'

  comfy_route :cms, path: '/', sitemap: false

end

app/models/product_group.rb
class ProductGroup < ActiveRecord::Base
  include Model::DelayedDestroy

  default_scope -> { where(remove_at: nil) }

  belongs_to :owner, class_name: User, inverse_of: :product_groups
  belongs_to :team
  has_many :arguments, inverse_of: :product_group, dependent: :destroy

  delegate :count, to: :arguments, prefix: true

  validates :name, presence: true
  validates :team, presence: true

  scope :active_only, -> { where(archived_at: nil) }
  scope :sorted, -> { order(:position) }

  acts_as_list scope: [:team, :remove_at]

  before_validation :store_team_from_owner, on: :create

  def archive=(val)
    self.archived_at = val.eql?('true') ? Time.zone.now : nil
  end

  def removable_by?(user)
    arguments_count.zero? || owner_id == user.id
  end

  alias_method :original_do_not_remove!, :do_not_remove!
  alias_method :original_remove!, :remove!

  def remove!
    remove_from_list
    original_remove!
  end

  def do_not_remove!
    original_do_not_remove!
    move_to_bottom
  end

  private

  def store_team_from_owner
    self.team_id = owner.team_id
  end
end

app/controllers/manager/arguments_controller.rb
class Manager::ArgumentsController < Manager::ManagerController
  def destroy
    success = Manager::DestroyArgument.call(self).success?
    redirect_to :back, notice: (success ? t('manager.arguments.destroy.notifications.success') : t('manager.arguments.destroy.notifications.failure'))
  end
end

app/controllers/manager/manager_controller.rb
class Manager::ManagerController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_manager!

  layout 'manager'

  private

  def authorize_manager!
    authorization_checks.each do |notice, check|
      unless check.call
        redirect_to root_path(locale: I18n.locale), alert: notice
        break
      end
    end
  end

  def authorization_checks
    [
      [t('common.unauthorized'), -> { current_user.manager? }],
      [t('subscriptions.subscription_expired_or_invalid'), -> { company_subscription.can_use_system? }]
    ]
  end
end

app/controllers/manager/product_groups_controller.rb
class Manager::ProductGroupsController < Manager::ManagerController
  expose_decorated(:product_groups, ancestor: :team) { |relation| relation.sorted.page(params[:page]) }
  expose(:product_group, attributes: :product_group_params)

  def show
    render json: product_group, root: false
  end

  def create
    product_group.owner = current_user

    if product_group.save
      redirect_to edit_manager_product_group_path(product_group, locale: I18n.locale)
    else
      render :index
    end
  end

  def edit
    gon.routes_prefix = root_path(locale: I18n.locale)
    gon.product_group_id = product_group.id
  end

  def update
    respond_to do |format|
      format.json do
        if Manager::UpdateProductGroup.call(self).success?
          render json: 'success', status: :ok
        else
          render json: 'invalid', status: :unprocessable_entity
        end
      end
      format.html do
        if Manager::UpdateProductGroupPublishStatus.call(self).success?
          redirect_to :back, notice: t('manager.product_groups.update.notifications.success')
        else
          redirect_to :back, error: t('manager.product_groups.update.notifications.failure')
        end
      end
    end
  end

  def destroy
    Manager::DestroyProductGroup.call(self)
    redirect_to :back, notice: t('manager.product_groups.destroy.notifications.success')
  end

  def sort
    product_group = product_groups.find(params[:id])
    product_group.insert_at(params[:position].to_i)
    head :ok
  end

  private

  def team
    current_user.team
  end

  def product_group_params
    params.require(:product_group).permit(:archive, :name)
  end
end

app/controllers/manager/profiles_controller.rb
class Manager::ProfilesController < Manager::ManagerController
  expose(:sales_reps_count) { current_user.team.sales_representatives.count }

  def update
    current_user.attributes = user_params
    if current_user.save
      redirect_to edit_manager_profile_path(locale: I18n.locale), notice: t('manager.profile.update.notifications.success')
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:display_name, :address)
  end
end

app/controllers/manager/reports/argument_rankings_controller.rb
class Manager::Reports::ArgumentRankingsController < Manager::ManagerController
  expose_decorated(:arguments, decorator: ReportArgumentRankingDecorator, collection: true) do
    current_user.team.arguments.includes(:product_group).order('cached_rating DESC NULLS LAST')
  end
end

app/controllers/manager/reports/dashboard_controller.rb
class Manager::Reports::DashboardController < Manager::ManagerController
end

app/controllers/manager/reports/user_activities_controller.rb
class Manager::Reports::UserActivitiesController < Manager::ManagerController
  expose(:users) { UserGamificationScoring.results_for_company_user(current_user) }
end

app/controllers/manager/users_controller.rb
class Manager::UsersController < Manager::ManagerController
  expose_decorated(:users, ancestor: :team) { |relation| relation.order(:email).page(params[:page]) }
  expose(:user, attributes: :user_params)

  def create
    if Manager::CreateUser.call(self).success?
      redirect_to manager_users_path(locale: I18n.locale), notice: t('manager.users.create.notifications.success')
    else
      flash.now[:alert] = t('manager.users.create.notifications.failure')
      render :index
    end
  end

  def destroy
    if Manager::DestroyUser.call(self).success?
      redirect_to manager_users_path(locale: I18n.locale), notice: t('manager.users.destroy.notifications.success')
    else
      redirect_to manager_users_path(locale: I18n.locale), alert: t('manager.users.destroy.notifications.failure')
    end
  end

  def update
    if Manager::UpdateUser.call(self).success?
      redirect_to manager_users_path(locale: I18n.locale), notice: t('manager.users.update.notifications.success')
    else
      render :edit
    end
  end

  private

  def team
    current_user.team
  end

  def user_params
    params.require(:user).permit(:display_name, :email, :invitation_message)
  end
end

app/views/manager/product_groups/edit.html.haml
.my-account
  .col-sm-9.col-md-8.col-md-offset-1
    %div{'ng-app' => 'editProductGroupApp', 'ng-controller' => 'editProductGroupCtrl'}
      %h4= t('manager.product_groups.edit.header', name: product_group.name)
      %label= t('common.name')
      %input.form-control{'ng-model' => 'productGroup.name', type: 'text', autofocus: true}

      %table.table.saapp-table
        %thead.arguments-readonly{'ng-hide' => 'hideHeaders()'}
          %th= t('common.feature')
          %th= t('common.benefit')
          %th
        %tbody
          %tr{'ng-repeat' => 'argument in arguments'}
            %td{'ng-hide' => 'argument.is_editable'}
              {{argument.feature}}
            %td{'ng-hide' => 'argument.is_editable'}
              {{argument.benefit}}
            %td{'ng-hide' => 'argument.is_editable'}
              %a.btn-icon.icon-trash{'ng-click' => 'removeArgument(argument)'}

      %ul.product-groups
        %li{'ng-repeat' => 'argument in arguments'}
          .row{'ng-show' => 'argument.is_editable'}
            .col-sm-5
              %input.form-control{'ng-model' => 'argument.feature', type: 'text'}
            .col-sm-5
              %input.form-control{'ng-model' => 'argument.benefit', type: 'text'}
            .col-sm-2
              %a.btn-icon.icon-trash{'ng-show' => 'argument.is_removable', 'ng-click' => 'removeArgument(argument)'}

      %form{name: 'newArgumentForm', 'ng-submit' =>'addArgument()'}
        %h4= t('manager.product_groups.edit.add_argument')
        .row
          .col-sm-6
            %label
              = t('common.feature')
              %i.icon-help{data:{toggle: 'tooltip'}, title: t('common.feature_description')}
            %input.form-control{'ng-model' => 'argument.feature', type: 'text', required: true}
          .col-sm-6
            %label
              = t('common.benefit')
              %i.icon-help{data:{toggle: 'tooltip'}, title: t('common.benefit_description')}
            %input.form-control.add-benefit{'ng-model' => 'argument.benefit', type: 'text', required: true}
            %input.wizard-add.four-corners.pull-right{type: 'submit', value: t('common.add')}
        .pull-right
          = link_to t('common.cancel'), manager_product_groups_path(locale: I18n.locale), class: 'btn btn-dark'
          %span.or
            = t('common.or')
          %button.btn.btn-primary{type: 'button', 'ng-click' => 'submitProductGroup()', 'ng-disabled' => 'canSaveProductGroup()'}
            = t('common.save_changes')

%script
  $('.icon-help').tooltip()

app/views/manager/product_groups/index.html.haml
.my-account
  .col-sm-9.col-md-8.col-md-offset-1
    %h4= t('manager.tabs.product_groups')
    %table.table.saapp-table-product-groups
      %thead
        %th
        %th= t('manager.product_groups.index.table.headers.product_group_name')
        %th= t('manager.product_groups.index.table.headers.arguments_count')
        %th
          .table-actions= t('manager.product_groups.index.table.headers.actions')
      %tbody.sortable
        - product_groups.each do |product_group|
          %tr{data: {id: product_group.id}}
            %td
              %span.icon-drag
            %td= product_group.name
            %td= product_group.arguments_count
            %td.text-center
              = product_group.publishing_link
              = product_group.edit_link
              = product_group.removal_link
    = paginate product_groups

    = simple_form_for product_group, url: manager_product_groups_path(locale: I18n.locale) do |f|
      .row-dark
        .col-md-7
          = f.input :name, label: false, placeholder: t('manager.product_groups.index.table.headers.product_group_name')
        .col-md-5
          = f.submit class: 'btn btn-primary btn-block'

:javascript
  $(function() {
    $('.sortable').sortable({
      placeholder: "ui-state-highlight",
      axis: "y",
      update: function(event, ui) {
        var blockedUI = $.blockUI({message: null});
        $.post(Routes.sort_manager_product_group_path(ui.item.data('id')), {position: ui.item.index() + 1}, function(data) {
        }).always(function() {
          $.unblockUI();
        });
      }
    });
    $('.sortable').disableSelection();
  });