config/routes.rb
Rails.application.routes.draw do
  resource :language, only: [:update]

  scope "(:locale)", locale: /da/, defaults: {locale: 'en'} do
    namespace :saasy do
      resources :callbacks, only: [:create]
      resources :subscriptions, only: [:show]
    end

    as :user do
      patch 'confirmation' => 'confirmations#update', as: :update_user_confirmation, controller: 'confirmations'
    end

    devise_for :users, {
      path: '',
      path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        sign_out_via: [:delete]
      },
      controllers: {
        confirmations: 'confirmations',
        sessions: 'sessions'
      }
    }

    ActiveAdmin.routes(self)

    root 'home#show'

    resources :wizards, only: [:new, :create]

    get 'autologin/:id' => 'autologins#login', as: :autologin

    namespace :manager do
      root 'profiles#edit'
      resource :profile, only: [:edit, :update]
      resources :product_groups, only: [:index, :show, :create, :edit, :update, :destroy] do
        post :sort, on: :member
      end
      resources :arguments, only: [:destroy]
      resources :users, only: [:index, :create, :edit, :update, :destroy]
      namespace :reports do
        root 'dashboard#show'
        resource :user_activity, only: [:show]
        resource :argument_ranking, only: [:show]
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :auth, only: [:create]
      match 'resources', to: 'resources#index', via: [:get, :post]
      resource :passwords, only: [:create, :update]
      resource :profile, only: [:show] do
        resource :avatar, only: [:update]
      end
      resources :arguments, only: [:create, :update] do
        resource :ratings, only: [:create]
      end
    end
  end

  comfy_route :cms_admin, path: '/admin/cms'

  comfy_route :cms, path: '/', sitemap: false

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:wizard)
end

app/views/home/_wizard_field.html.haml
= content_for :landing do
  .landing
    .landing-devices
      = link_to '', {'data-target' => '#videoModal', 'data-toggle' => 'modal'}, class: 'landing-play' do
        .icon-play

      #videoModal.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'videoModalLabel', :role => 'dialog', :tabindex => '-1'}
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', :type => 'button'}
                %span{'aria-hidden' => 'true'} ×
            .modal-body
              .video-container
                %iframe{allowfullscreen: '', frameborder: '0', src: 'https://www.youtube.com/embed/YrVdo9MIe5E'}

- if guest?
  .landing-form.clearfix
    = simple_form_for wizard, method: :get, url: new_wizard_path(locale: I18n.locale) do |f|
      = f.input :email, input_html: {tabindex: 1, autocomplete: 'off'}
      = f.submit t('helpers.submit.wizard.create'), class: 'btn btn-primary', tabindex: 2

:javascript
  $("#videoModal").on('show.bs.modal', function (e) {
    video = $(this).find('iframe').attr("src");
    video += '?autoplay=1'
    $(this).find('iframe').attr("src", video)
  });

  $("#videoModal").on('hidden.bs.modal', function (e) {
      video = $(this).find('iframe').attr("src").replace('?autoplay=1', '');
      $("#videoModal iframe").attr("src", video);
  });

app/views/home/show.html.haml
= render inline: cms_root_page_content